name: Deploy App to S3
description: Upload Build app to S3 Bucket

inputs:
  aws-region:
    required: true
    description: AWS region

  aws-s3-bucket:
    required: true
    description: The name of the S3 bucket

  local-directory:
    description: The local directory to upload
    default: ./frontend/dist

  destination:
    description: The directory inside of the S3 bucket
    default: build

runs:
  using: 'composite'
  steps:
    - name: Upload to S3 Bucket (without index.html)
      shell: bash
      run: |
        aws s3 sync ${{ inputs.local-directory }} s3://${{ inputs.aws-s3-bucket }}/${{ inputs.destination }} \
                --region ${{ inputs.aws-region }} \
                --no-progress \
                --follow-symlinks \
                --delete \
                --cache-control max-age=604800 \
                --exclude 'index.html'

    - name: Upload index.html to S3 Bucket
      shell: bash
      run: |
        aws s3 cp ${{ inputs.local-directory }}/index.html s3://${{ inputs.aws-s3-bucket }}/${{ inputs.destination }}/index.html \
                --region ${{ inputs.aws-region }} \
                --cache-control max-age=0 \
